package com.jewel.ecom.hateoas;


import static java.util.stream.Collectors.toList;
import static org.springframework.hateoas.server.mvc.WebMvcLinkBuilder.linkTo;
import static org.springframework.hateoas.server.mvc.WebMvcLinkBuilder.methodOn;

import java.util.List;
import java.util.Objects;
import java.util.stream.StreamSupport;

import com.jewel.ecom.api.model.Address;
import com.jewel.ecom.controller.AddressController;
import com.jewel.ecom.entity.AddressEntity;
import org.springframework.beans.BeanUtils;
import org.springframework.hateoas.server.mvc.RepresentationModelAssemblerSupport;
import org.springframework.stereotype.Component;


@Component
public class AddressRepresentationModelAssembler extends
        RepresentationModelAssemblerSupport<AddressEntity, Address> {

    /**
     * Creates a new {@link RepresentationModelAssemblerSupport} using the given controller class and
     * resource type.
     */
    public AddressRepresentationModelAssembler() {
        super(AddressController.class, Address.class);
    }

    /**
     * Coverts the Address entity to resource
     *
     * @param entity
     */
    @Override
    public Address toModel(AddressEntity entity) {
        Address resource = createModelWithId(entity.getId(), entity);
        BeanUtils.copyProperties(entity, resource);
        resource.setId(entity.getId().toString());
        // Self link generated by createModelWithId has missing api path. Therefore, generating additionally.
        // can be removed once fixed.
        try {
            resource.add(
                    linkTo(methodOn(AddressController.class).getAddressesById(entity.getId().toString()))
                            .withSelfRel());
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        return resource;
    }

    /**
     * Coverts the collection of Product entities to list of resources.
     *
     * @param entities
     */
    public List<Address> toListModel(Iterable<AddressEntity> entities) {
        if (Objects.isNull(entities)) {
            return List.of();
        }
        return StreamSupport.stream(entities.spliterator(), false).map(this::toModel)
                .collect(toList());
    }

}